services:
  api:
    build:
      context: ./api
    container_name: idolmaster-tours-livephoto-api
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - TZ=Asia/Tokyo
      - PORT=8000

  web:
    build:
      context: ./web
    container_name: idolmaster-tours-livephoto-web
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - api